export type BlogPost = {
  href: string;
  image: string;
  alt: string;
  date: string;
  title: string;
  excerpt: string;
  featured?: boolean;
};

export const BLOG_HERO =
  "/images/2025/11/truck-repair-in-shop.jpg";

export const BLOG_POSTS: BlogPost[] = [
  {
    href: 'https://srbequipment.ca/blog/truck-parts-that-need-to-be-replaced-regularly/',
    image: '/images/2026/02/heavy-duty-truck-parts-places-on-a-table.jpg',
    alt: 'Heavy Duty Truck Parts Maintenance Guide',
    date: 'Feb 26, 2026',
    title: 'Heavy Duty Truck Parts Maintenance Guide',
    excerpt: 'Some truck parts are essential to be replaced after a certain period to avoid any huge problems and accidents in the vehicle. We have listed down the truck parts that are essential to be replaced to m…',
    featured: true,
  },
  {
    href: 'https://srbequipment.ca/blog/why-is-proper-wheel-alignment-crucial-for-trucks/',
    image: '/images/2024/01/srb-equipment-technician-inspecting-semi-truck-wheels-in-shop.jpg',
    alt: 'Why Is Proper Wheel Alignment Crucial For Trucks And Other Heavy Vehicles?',
    date: 'Feb 20, 2026',
    title: 'Why Is Proper Wheel Alignment Crucial For Trucks And Other Heavy Vehicles?',
    excerpt: 'Learn why proper truck wheel alignment is essential for fuel efficiency, tire life, steering control, and preventing costly repairs in heavy-duty vehicles.',
  },
  {
    href: 'https://srbequipment.ca/blog/heavy-duty-mechanic-career-guide/',
    image: '/images/2026/02/Untitled-design-2-2.jpg',
    alt: 'Heavy Duty Mechanic Career Guide 2026',
    date: 'Feb 18, 2026',
    title: 'Heavy Duty Mechanic Career Guide 2026',
    excerpt: 'Learn how to become a heavy-duty mechanic in 2026. Discover skills, training, certifications, salary potential, and career growth opportunities.',
  },
  {
    href: 'https://srbequipment.ca/blog/top-engine-maintenance-tips-for-your-kenworth-w900/',
    image: '/images/2026/02/kenworth-w900-blue-color-heavy-duty-truck.jpg',
    alt: 'Top Engine Maintenance Tips for Your Kenworth W900',
    date: 'Feb 17, 2026',
    title: 'Top Engine Maintenance Tips for Your Kenworth W900',
    excerpt: 'Protect your Kenworth W900 engine with expert service tips covering oil changes, fuel filters, cooling systems, and preventive diesel truck maintenance.',
  },
  {
    href: 'https://srbequipment.ca/blog/emergency-roadside-repair-tips-for-trucks/',
    image: '/images/2026/02/emergency-roadside-truck-repaired-by-srb-equipment-mobile-service.jpg',
    alt: 'Emergency Roadside Service For Commercial Truck Repair in Edmonton',
    date: 'Jun 13, 2025',
    title: 'Emergency Roadside Service For Commercial Truck Repair in Edmonton',
    excerpt: 'Learn how emergency roadside truck service in Edmonton handles breakdowns, tires, batteries, fuel issues, and keeps drivers safe on the road.',
  },
  {
    href: 'https://srbequipment.ca/blog/peterbilt-579-truck-repair-solutions/',
    image: '/images/2026/01/34.webp',
    alt: 'How to Troubleshoot and Fix Common Issues With the Peterbilt Model 579',
    date: 'Jun 7, 2025',
    title: 'How to Troubleshoot and Fix Common Issues With the Peterbilt Model 579',
    excerpt: 'The Peterbilt 579 is built for long trips, but it can still face issues. This guide covers common problems, simple fixes, and maintenance tips to help keep your truck running smoothly across Canada’s …',
  },
  {
    href: 'https://srbequipment.ca/blog/pto-wet-kit-for-trucks/',
    image: '/images/2025/05/Untitled-design.jpg',
    alt: 'Everything You Should Know About PTO Wet Kit for Trucks',
    date: 'May 29, 2025',
    title: 'Everything You Should Know About PTO Wet Kit for Trucks',
    excerpt: 'Discover how a PTO wet kit works and why it’s vital for semi trucks. Get expert installation help from SRB Equipment today!',
  },
  {
    href: 'https://srbequipment.ca/blog/winter-truck-maintenance-tips/',
    image: '/images/2025/05/Untitled-5.jpg',
    alt: 'Winter Truck Maintenance Tips: Keep Your Truck Safe in Cold Weather',
    date: 'May 22, 2025',
    title: 'Winter Truck Maintenance Tips: Keep Your Truck Safe in Cold Weather',
    excerpt: 'Learn how to protect your truck in winter with easy maintenance tips. Avoid breakdowns, engine damage, and battery failure. Book your service today.',
  },
  {
    href: 'https://srbequipment.ca/blog/truck-air-filter-replacement-tips/',
    image: '/images/2025/05/Untitled-design-8.jpg',
    alt: 'Truck Air Filter Replacement: What Every Driver Needs to Know',
    date: 'May 15, 2025',
    title: 'Truck Air Filter Replacement: What Every Driver Needs to Know',
    excerpt: 'Learn how diesel truck air filter replacement improves engine performance, fuel efficiency, and reliability. Signs, steps, and maintenance tips included.',
  },
  {
    href: 'https://srbequipment.ca/blog/choosing-right-coolant-for-truck-engine/',
    image: '/images/2025/05/0-1.jpg',
    alt: 'Why Choosing the Right Coolant Matters for Your Truck’s Engine in Canada?',
    date: 'May 12, 2025',
    title: 'Why Choosing the Right Coolant Matters for Your Truck’s Engine in Canada?',
    excerpt: 'Learn why choosing the right coolant is crucial for your truck’s engine performance, longevity, and protection in Canada’s extreme weather.',
  },
  {
    href: 'https://srbequipment.ca/blog/truck-clutch-replacement-cost-edmonton/',
    image: '/images/2026/03/heavy-duty-clutch-friction-disc-and-diaphragm-spring-mechanism.jpg',
    alt: 'How Much Does Truck Clutch Replacement Cost for Heavy Duty Trucks',
    date: 'Apr 29, 2025',
    title: 'How Much Does Truck Clutch Replacement Cost for Heavy Duty Trucks',
    excerpt: 'How much does a semi truck clutch replacement cost in Edmonton? See real price ranges, labor estimates, and what affects your total bill.',
  },
  {
    href: 'https://srbequipment.ca/blog/why-truck-overheating-causes/',
    image: '/images/2025/04/truck-overheating-image.jpg',
    alt: 'Truck Overheating? Here’s Why & How to Fix It Fast!',
    date: 'Apr 24, 2025',
    title: 'Truck Overheating? Here’s Why & How to Fix It Fast!',
    excerpt: 'Is your truck overheating? Learn the causes, easy fixes, and expert tips to prevent engine damage. Keep your truck cool with these proven solutions!',
  },
  {
    href: 'https://srbequipment.ca/blog/how-regular-engine-maintenance-affects-fuel-economy-and-money-savings/',
    image: '/images/2023/08/How-Regular-Engine-Maintenance-Affects-Fuel-Economy-and-Money-Savings_Image.jpg',
    alt: 'How Regular Engine Maintenance Affects Fuel Economy and Money Savings',
    date: 'Feb 7, 2025',
    title: 'How Regular Engine Maintenance Affects Fuel Economy and Money Savings',
    excerpt: 'Sticking to a regular engine maintenance schedule ensures your vehicle operates optimally, extending its lifespan and reducing costly breakdowns. Moreover, it also helps save money on potential repair…',
  },
  {
    href: 'https://srbequipment.ca/blog/top-10-signs-paccar-truck-repair-edmonton/',
    image: '/images/2025/01/1-2.jpg',
    alt: 'Top 10 Signs Your Paccar Truck Needs Immediate Repair in Edmonton',
    date: 'Jan 30, 2025',
    title: 'Top 10 Signs Your Paccar Truck Needs Immediate Repair in Edmonton',
    excerpt: 'This blog highlights the top signs that your Paccar truck needs immediate attention, helping you avoid breakdowns and keep your truck in top shape.',
  },
  {
    href: 'https://srbequipment.ca/blog/heavy-duty-diesel-truck-lighting-problems/',
    image: '/images/2024/04/diesel-truck-lighting-image.jpg',
    alt: 'Diesel Truck Lighting: Issues, Symptoms, and Quick Fixes',
    date: 'Jan 13, 2025',
    title: 'Diesel Truck Lighting: Issues, Symptoms, and Quick Fixes',
    excerpt: 'When it comes to heavy-duty diesel trucks, maintaining a fully functional lighting system is crucial for safety and efficiency on the road. Whether you’re managing a fleet or operating a single truck,…',
  },
  {
    href: 'https://srbequipment.ca/blog/why-choose-experienced-truck-repair-facilities-in-edmonton/',
    image: '/images/2023/04/choose-experienced-truck-repair-facilities-image.jpg',
    alt: 'Why Choose Experienced Truck Repair Facilities In Edmonton?',
    date: 'Jan 3, 2025',
    title: 'Why Choose Experienced Truck Repair Facilities In Edmonton?',
    excerpt: 'Choosing an experienced truck repair facility in Edmonton means faster, reliable service from certified technicians using the right tools and quality parts. This blog explains why expertise matters to…',
  },
  {
    href: 'https://srbequipment.ca/blog/warning-signs-your-heavy-duty-truck-requires-exhaust-system-repair/',
    image: '/images/2024/09/top-warning-signs-your-heavy-duty-truck-requires-exhaust-system-repair-image.jpg',
    alt: 'Top Warning Signs Your Heavy-Duty Truck Requires Exhaust System Repair',
    date: 'Sep 5, 2024',
    title: 'Top Warning Signs Your Heavy-Duty Truck Requires Exhaust System Repair',
    excerpt: 'In this blog, we’ll dive into the key indicators that suggest your truck’s exhaust system requires attention, explore common causes behind these issues, and guide you on how to choose the best exhaust…',
  },
  {
    href: 'https://srbequipment.ca/blog/top-signs-that-your-trucks-axle-needs-repair/',
    image: '/images/2024/08/truck-axle-repair-edmonton-image.jpg',
    alt: 'Top Signs That Your Truck’s Axle Needs Repair',
    date: 'Aug 29, 2024',
    title: 'Top Signs That Your Truck’s Axle Needs Repair',
    excerpt: 'Axle issues in heavy-duty trucks often start with subtle warning signs like vibrations, clunking noises, or uneven tire wear. Ignoring these symptoms can lead to costly breakdowns and safety risks. Th…',
  },
  {
    href: 'https://srbequipment.ca/blog/top-benefits-of-ecm-tuning-for-diesel-engines-trucks/',
    image: '/images/2024/08/ecm-tuning-for-diesel-engines-trucks-image-.jpg',
    alt: 'Save Money and Fuel: Top Benefits of ECM Tuning for Diesel Engines Trucks',
    date: 'Aug 21, 2024',
    title: 'Save Money and Fuel: Top Benefits of ECM Tuning for Diesel Engines Trucks',
    excerpt: 'Boost your truck’s power, cut fuel costs, and enjoy smoother drives with ECM tuning. Learn how this upgrade improves performance, saves money, and extends engine life effortlessly.',
  },
  {
    href: 'https://srbequipment.ca/blog/top-cvip-inspection-failures/',
    image: '/images/2024/08/top-cvip-inspection-failures-and-tips-to-prevent-them-image.jpg',
    alt: 'Top CVIP Inspection Failures and Tips to Prevent Them',
    date: 'Aug 1, 2024',
    title: 'Top CVIP Inspection Failures and Tips to Prevent Them',
    excerpt: 'Get expert tips on the CVIP inspection checklist, common failures, and how to pass. Stay road-safe and compliant with expert advice from SRB Equipment.',
  },
  {
    href: 'https://srbequipment.ca/blog/cold-weather-tire-care-for-heavy-duty-trucks/',
    image: '/images/2024/05/Expert-Tips-Cold-Weather-Tire-Care-for-Heavy-Duty-Trucks_image.jpg',
    alt: 'Expert Tips: Cold Weather Tire Care for Heavy-Duty Trucks',
    date: 'May 16, 2024',
    title: 'Expert Tips: Cold Weather Tire Care for Heavy-Duty Trucks',
    excerpt: 'Winter roads can be tough on heavy-duty truck tires. This blog shares essential cold weather tire care tips to help you stay safe, improve traction, and extend tire life during the colder months.',
  },
  {
    href: 'https://srbequipment.ca/blog/top-semi-truck-repair-shop-for-your-fleet/',
    image: '/images/2024/05/top-semi-truck-repair-facility_image.jpg',
    alt: 'What To Look Out For When Searching For The Top Semi-Truck Repair Shop For Your Fleet.',
    date: 'May 8, 2024',
    title: 'What To Look Out For When Searching For The Top Semi-Truck Repair Shop For Your Fleet.',
    excerpt: 'Selecting the right truck repair shop is a big deal for you and your truck. The right choice will prolong the lifespan of your truck and enlarge the profit in return. The wrong one will reduce the lif…',
  },
  {
    href: 'https://srbequipment.ca/blog/the-importance-of-professional-truck-repair-keeping-your-fleet-on-the-road/',
    image: '/images/2024/05/professional-truck-repair_image.jpg',
    alt: 'The Importance of Professional Truck Repair: Keeping Your Fleet on the Road',
    date: 'May 1, 2024',
    title: 'The Importance of Professional Truck Repair: Keeping Your Fleet on the Road',
    excerpt: 'When it comes to keeping your fleet on the road, professional truck repair services play a crucial role. These experts have the specialized knowledge and equipment to handle everything from routine in…',
  },
  {
    href: 'https://srbequipment.ca/blog/maintaining-and-repairing-hydraulic-systems-of-heavy-duty-truck/',
    image: '/images/2024/04/repairing-hydraulic-systems-of-heavy-duty-truck_image.jpg',
    alt: 'Tips For Maintaining And Repairing Hydraulic Systems of Heavy-Duty Truck',
    date: 'Apr 23, 2024',
    title: 'Tips For Maintaining And Repairing Hydraulic Systems of Heavy-Duty Truck',
    excerpt: 'Discover expert tips to maintain and repair your heavy-duty truck’s hydraulic system. Learn how to inspect, clean, and troubleshoot common hydraulic issues.',
  },
  {
    href: 'https://srbequipment.ca/blog/peterbilt-truck-maintenance/',
    image: '/images/2024/03/Understanding-Peterbilt-Truck-Maintenance-Schedules-A-Comprehensive-Guide_image.jpg',
    alt: 'Understanding Peterbilt Truck Maintenance Schedules: A Comprehensive Guide',
    date: 'Mar 28, 2024',
    title: 'Understanding Peterbilt Truck Maintenance Schedules: A Comprehensive Guide',
    excerpt: 'If you want to ensure your trucking operation is running at its best with Peterbilt, consider investing in preventive maintenance. By staying proactive with maintenance checks and servicing, you can e…',
  },
  {
    href: 'https://srbequipment.ca/blog/ford-truck-repair-in-edmonton/',
    image: '/images/2024/02/Driving-with-Confidence-Ford-Truck-Repair-in-Edmonton_Image.jpg',
    alt: 'Driving with Confidence: Ford Truck Repair in Edmonton',
    date: 'Feb 12, 2024',
    title: 'Driving with Confidence: Ford Truck Repair in Edmonton',
    excerpt: 'A well-maintained Ford truck is not just a reliable companion; it’s an investment in the longevity and performance of your vehicle. Whether you use your Ford truck for work or a long drive, taki…',
  },
  {
    href: 'https://srbequipment.ca/blog/discover-how-ecm-tuning-can-help/',
    image: '/images/2023/09/Is-Your-Truck-Underperforming_Image.jpg',
    alt: 'Is Your Truck Underperforming? Discover How ECM Tuning Can Help',
    date: 'Sep 15, 2023',
    title: 'Is Your Truck Underperforming? Discover How ECM Tuning Can Help',
    excerpt: 'ECM tuning, also known as engine control module tuning or ECU tuning, might be a solution to reignite that lost spark and restore your truck’s performance.',
  },
  {
    href: 'https://srbequipment.ca/blog/how-to-drive-safely-your-semi-truck-in-heavy-rain/',
    image: '/images/2023/08/How-to-Drive-Safely-Your-Semi-Truck-in-Heavy-Rain-Safety-Tips-Dangers_image.jpg',
    alt: 'How to Drive a Semi-Truck Safely in Heavy Rain: Expert Tips for Truckers',
    date: 'Aug 10, 2023',
    title: 'How to Drive a Semi-Truck Safely in Heavy Rain: Expert Tips for Truckers',
    excerpt: 'Drive your semi-truck safely in heavy rain with expert tips to avoid hydroplaning, boost visibility & stay in control. Read the full guide by SRB Equipment now.',
  },
  {
    href: 'https://srbequipment.ca/blog/truck-emission-system-failure-most-common-signs/',
    image: '/images/2023/06/Truck-Emission-System-Failure-Most-Common-Signs-_image1.jpg',
    alt: 'Truck Emission System Failure: Most Common Signs.',
    date: 'Jun 26, 2023',
    title: 'Truck Emission System Failure: Most Common Signs.',
    excerpt: 'Every component should work fully to ensure the engine runs smoothly. If damaged, it can cause a huge blunder.Watch out for these Signs that indicate that your truck’s emission system has failed and n…',
  },
  {
    href: 'https://srbequipment.ca/blog/heavy-duty-truck-radiator-repair/',
    image: '/images/2023/06/Heavy-Duty-Truck-Radiator-Repair-What-Is-Cooling-System-Repair_image.jpg',
    alt: 'Heavy Duty Truck Radiator Repair: What Is Cooling System Repair?',
    date: 'Jun 9, 2023',
    title: 'Heavy Duty Truck Radiator Repair: What Is Cooling System Repair?',
    excerpt: 'However, when the cooling system is not working properly and has been damaged, it shows some indications you need to identify.Before we know if the cooling system is damaged, let’s first see what the …',
  },
  {
    href: 'https://srbequipment.ca/blog/professional-commercial-vehicle-repair-shop/',
    image: '/images/2023/05/The-Benefits-Of-Working-With-A-Professional-Commercial-Vehicle-Repair-Shop_image.jpg',
    alt: 'The Benefits Of Working With A Professional Commercial Vehicle Repair Shop',
    date: 'May 12, 2023',
    title: 'The Benefits Of Working With A Professional Commercial Vehicle Repair Shop',
    excerpt: 'There are many reasons to choose a professional Commercial vehicle repair shop because you surely don’t want to pay for repair every time when it just costs you repair in the next 2-3 months.',
  },
  {
    href: 'https://srbequipment.ca/blog/3-mistakes-to-avoid-when-choosing-a-pick-up-truck-wheel-balancing-shop/',
    image: '/images/2023/05/3-mistakes-to-avoid-when-choosing-a-pick-up-truck-wheel-balancing-shop_image.jpg',
    alt: '3 Mistakes to Avoid When Choosing a Pick-Up Truck Wheel Balancing Shop.',
    date: 'May 6, 2023',
    title: '3 Mistakes to Avoid When Choosing a Pick-Up Truck Wheel Balancing Shop.',
    excerpt: 'Choosing the best Pick-up Truck Wheel Balancing shop is very necessary. Maintaining your truck to ensure maximum safety for your deliveries is important. Most truck owners make the mistake of not main…',
  },
  {
    href: 'https://srbequipment.ca/blog/bring-your-truck-to-a-truck-repair-shop-before-winter/',
    image: '/images/2023/04/truck-at-repair-shop-image.jpg',
    alt: 'Reasons to Bring Your Truck to a Truck Repair Shop Before Winter',
    date: 'Apr 12, 2023',
    title: 'Reasons to Bring Your Truck to a Truck Repair Shop Before Winter',
    excerpt: 'By taking on pre-trip checks and evaluating the performance of your heavy-duty truck’ components, you can avoid long-term maintenance challenges and save your business thousands of dollars. This lates…',
  },
  {
    href: 'https://srbequipment.ca/blog/5-basic-maintenance-tips-for-your-truck/',
    image: '/images/2023/04/basic-maintenance-tips-for-your-truck-image.png',
    alt: '5 Basic Maintenance Tips for your Truck.',
    date: 'Apr 11, 2023',
    title: '5 Basic Maintenance Tips for your Truck.',
    excerpt: 'Here are 5 basic maintenance tips for your truck which helps to keep it running at its best for years to come. Let’s know about them.',
  },
  {
    href: 'https://srbequipment.ca/blog/how-often-should-you-see-a-diesel-mechanic-for-your-semi-truck/',
    image: '/images/2023/04/How-Often-Should-You-See-a-Diesel-Mechanic-for-Your-Semi-Truck_image.jpg',
    alt: 'How Often Should You See a Diesel Mechanic for Your Semi-Truck?',
    date: 'Apr 10, 2023',
    title: 'How Often Should You See a Diesel Mechanic for Your Semi-Truck?',
    excerpt: 'In today’s blog, we will cover the complete details of how you can receive the best truck repair service in Edmonton and everything you need to consider.',
  },
  {
    href: 'https://srbequipment.ca/blog/why-every-trucking-company-needs-a-truck-repair-shop/',
    image: '/images/2022/11/Why-Every-Trucking-Company-Needs-a-Truck-Repair-Shop.jpg',
    alt: 'Why Every Trucking Company Needs a Truck Repair Shop',
    date: 'Apr 10, 2023',
    title: 'Why Every Trucking Company Needs a Truck Repair Shop',
    excerpt: 'Even truckers or fleet owners who always stay on top of their truck maintenance experience breakdowns and unexpected problems on the road. When breakdowns happen, you need a truck repair shop that wil…',
  },
  {
    href: 'https://srbequipment.ca/blog/benefits-of-getting-routine-brake-service-for-your-truck/',
    image: '/images/2022/10/What-are-the-Benefits-of-Getting-Routine-Brake-Service-for-Your-Truck_img.jpg',
    alt: 'What are the Benefits of Getting Routine Brake Service for Your Truck?',
    date: 'Apr 8, 2023',
    title: 'What are the Benefits of Getting Routine Brake Service for Your Truck?',
    excerpt: 'Experts prefer truck owners to get their truck brakes checked at least twice a year.',
  },
  {
    href: 'https://srbequipment.ca/blog/what-should-you-know-about-cvip-inspections/',
    image: '/images/2022/09/What-Should-You-Know-About-CVIP-Inspections_image.jpg',
    alt: 'What Should You Know About CVIP Inspections?',
    date: 'Apr 6, 2023',
    title: 'What Should You Know About CVIP Inspections?',
    excerpt: 'In order to drive your vehicle in Canada, you must pass your vehicle through a CVIP, a.k.a. Commercial Vehicle Inspection Program. The motive of conducting vehicle inspections is to ensure that the ve…',
  },
  {
    href: 'https://srbequipment.ca/blog/when-should-you-change-the-oil-in-your-commercial-trucks/',
    image: '/images/2022/12/When-Should-You-Change-the-Oil-in-Your-Commercial-Trucks_image.jpg',
    alt: 'When Should You Change the Oil in Your Commercial Trucks?',
    date: 'Apr 5, 2023',
    title: 'When Should You Change the Oil in Your Commercial Trucks?',
    excerpt: 'Commercial vehicles have different oil change frequencies than other vehicles, and Knowing the proper time interval for an oil change can increase the age of your truck. Moreover, keeping your engine …',
  },
  {
    href: 'https://srbequipment.ca/blog/expensive-truck-repair-mistakes/',
    image: '/images/2023/04/expensive-truck-repair-mistakes-to-avoid.jpg',
    alt: '11 Most Expensive Truck Repair Mistakes and How to Avoid Them.',
    date: 'Apr 4, 2023',
    title: '11 Most Expensive Truck Repair Mistakes and How to Avoid Them.',
    excerpt: 'Truck ownership comes with its fair share of challenges, especially when it comes to maintenance and repairs. The trucking industry relies heavily on efficient truck performance, making truck repair a…',
  },
  {
    href: 'https://srbequipment.ca/blog/5-common-heavy-duty-truck-braking-problems-and-how-to-avoid-them/',
    image: '/images/2022/11/5-Common-Heavy-Duty-Truck-Braking-Problems-And-How-To-Avoid-Them.jpg',
    alt: '5 Common Heavy-Duty Truck Braking Problems And How To Avoid Them',
    date: 'Apr 4, 2023',
    title: '5 Common Heavy-Duty Truck Braking Problems And How To Avoid Them',
    excerpt: 'Having a damaged, improperly functioning, or worn-out brake system is a danger to all those on the roadways. Therefore, it’s crucial for drivers to be aware of brake issues and how to avoid them with …',
  },
  {
    href: 'https://srbequipment.ca/blog/how-to-prepare-your-diesel-truck-for-canadian-winters/',
    image: '/images/2022/11/How-to-Prepare-Your-Diesel-Truck-For-Canadian-Winters.jpg',
    alt: 'How to Prepare Your Diesel Truck For Canadian Winters',
    date: 'Apr 2, 2023',
    title: 'How to Prepare Your Diesel Truck For Canadian Winters',
    excerpt: 'Better to prepare for the worst—and do it now before the cold weather hits. Here’s how you and your truck can be proactive this winter:',
  },
  {
    href: 'https://srbequipment.ca/blog/basics-of-a-wheel-alignment/',
    image: '/images/2022/10/The-Basics-of-a-Tire-Alignment-How-to-Know-If-You-Need-One_image.png',
    alt: 'Truck Wheel Alignment Guide for Truckers & Fleet Owners',
    date: 'Mar 31, 2023',
    title: 'Truck Wheel Alignment Guide for Truckers & Fleet Owners',
    excerpt: 'Getting your wheels aligned regularly is one of the essential things you need to take care of when owning a truck.',
  },
  {
    href: 'https://srbequipment.ca/blog/5-signs-that-will-tell-you-its-time-to-change-your-trucks-brake-pads/',
    image: '/images/2022/12/5-Signs-That-Will-Tell-You-Its-Time-to-Change-Your-Trucks-Brake-Pads_Image.jpg',
    alt: '5 Signs That Will Tell You It’s Time to Change Your Truck’s Brake Pads',
    date: 'Mar 30, 2023',
    title: '5 Signs That Will Tell You It’s Time to Change Your Truck’s Brake Pads',
    excerpt: 'Brakes on trucks work hard because of the extra carriage weight they are stopping, so it is essential to recognize all signs they could be going bad. Is it time to change your brake pads? SRB Equipmen…',
  },
  {
    href: 'https://srbequipment.ca/blog/mistakes-to-avoid-when-doing-an-engine-rebuild-for-your-heavy-duty-truck/',
    image: '/images/2022/11/3-Mistakes-To-Avoid-When-Doing-an-Engine-Rebuild-For-Your-Heavy-Duty-Truck.jpg',
    alt: 'Top 3 Mistakes to Avoid During a Truck Engine Rebuild for Heavy-Duty Vehicles',
    date: 'Mar 29, 2023',
    title: 'Top 3 Mistakes to Avoid During a Truck Engine Rebuild for Heavy-Duty Vehicles',
    excerpt: 'Avoid costly engine rebuild mistakes with this simple guide. Learn what to watch for and get expert help in Edmonton from SRB Equipment when you need it—call us today!',
  },
  {
    href: 'https://srbequipment.ca/blog/what-vehicles-are-subject-to-the-cvip/',
    image: '/images/2022/11/What-Vehicles-Are-Subject-to-the-Commercial-Vehicle-Inspection-Program.jpg',
    alt: 'What Vehicles Are Subject to the Commercial Vehicle Inspection Program?',
    date: 'Mar 28, 2023',
    title: 'What Vehicles Are Subject to the Commercial Vehicle Inspection Program?',
    excerpt: 'The CVIP is the mandatory safety inspection program to operate any type of commercial vehicle over 4,500 kg or a bus with a seating capacity of more than 10 or equivalent.',
  },
  {
    href: 'https://srbequipment.ca/blog/5-most-common-truck-failures-problems-on-road/',
    image: '/images/2022/10/5-Most-Common-Truck-Failures-Problems-on-Road.jpg',
    alt: 'Top 5 Most Common Truck Failures on the Road',
    date: 'Mar 27, 2023',
    title: 'Top 5 Most Common Truck Failures on the Road',
    excerpt: 'Truck breakdowns cause delays, safety risks, and high repair costs. From brake failures to engine overheating, early warning signs are key. Learn the top 5 common truck issues and how to prevent them.…',
  },
  {
    href: 'https://srbequipment.ca/blog/how-to-identify-and-fix-electrical-issues-in-your-truck/',
    image: '/images/2023/03/How-to-Identify-and-Fix-Electrical-Issues-in-Your-Truck_image.jpg',
    alt: 'Truck Electric Repair – A Complete Guide for Every Truck Owner',
    date: 'Mar 25, 2023',
    title: 'Truck Electric Repair – A Complete Guide for Every Truck Owner',
    excerpt: 'Discover how to troubleshoot truck electrical issues. For expert repairs, reach out to SRB Equipment and keep your truck in top condition!',
  },
  {
    href: 'https://srbequipment.ca/blog/5-common-heavy-duty-truck-suspension-problems-and-how-to-avoid-them/',
    image: '/images/2022/12/5-Common-Heavy-Duty-Truck-Suspension-Problems-And-How-To-Avoid-Them_image.jpg',
    alt: '5 Common Heavy Duty Truck Suspension Problems And How To Avoid Them',
    date: 'Mar 25, 2023',
    title: '5 Common Heavy Duty Truck Suspension Problems And How To Avoid Them',
    excerpt: 'The suspension, which truck drivers mostly ignore, needs attention from time to time. A worn-out suspension system prevents you from controlling the vehicle when you stop or turn, which can lead to a …',
  },
  {
    href: 'https://srbequipment.ca/blog/how-to-find-best-truck-repair-shop-near-you/',
    image: '/images/2022/09/Truck-Repair-Tips-How-to-Find-the-Best-Truck-Repair-Shop-Near-You.jpg',
    alt: 'Tips to Find Best Truck Repair Shop Near You',
    date: 'Mar 24, 2023',
    title: 'Tips to Find Best Truck Repair Shop Near You',
    excerpt: 'When caught up in a circumstance where you have to take your truck for a Repair and you don’t know where to go, we got your back. To help you with this, we have penned down this blog. You can ea…',
  },
  {
    href: 'https://srbequipment.ca/blog/key-pointers-on-exhaust-and-emission-aftertreatment-systems/',
    image: '/images/2022/12/Key-Pointers-on-Exhaust-and-Emission-Aftertreatment-Systems_image.jpg',
    alt: 'Key Pointers on Exhaust and Emission Aftertreatment Systems',
    date: 'Mar 22, 2023',
    title: 'Key Pointers on Exhaust and Emission Aftertreatment Systems',
    excerpt: 'Diesel aftertreatment systems contribute significantly to pushing the clean diesel emission. Before that system, diesel has long had an image problem. They were famous for being noisy, slow, and dirty…',
  },
  {
    href: 'https://srbequipment.ca/blog/5-signs-that-indicate-that-your-truck-needs-repair/',
    image: '/images/2022/09/5-Signs-That-Indicate-That-Your-Truck-Needs-Repair_Image.jpg',
    alt: '5 Signs Your Heavy-Duty Truck Needs Repair',
    date: 'Mar 21, 2023',
    title: '5 Signs Your Heavy-Duty Truck Needs Repair',
    excerpt: 'Learn the top 5 signs your truck needs repair—dashboard alerts, fluid leaks, and more. Stay safe and avoid breakdowns. Book your service with SRB today!',
  },
  {
    href: 'https://srbequipment.ca/blog/how-much-are-heavy-duty-truck-repairs-in-edmonton/',
    image: '/images/2022/10/How-Much-Are-Heavy-Duty-Truck-Repairs-In-Edmonton_image.jpg',
    alt: 'How Much Are Heavy-Duty Truck Repairs In Edmonton?',
    date: 'Mar 21, 2023',
    title: 'How Much Are Heavy-Duty Truck Repairs In Edmonton?',
    excerpt: 'If you own a heavy-duty truck, one thing that you have to be ready for is to pay a heavy amount for its repair. If you are curious about how much it will cost to repair your heavy-duty truck, then let…',
  },
  {
    href: 'https://srbequipment.ca/blog/key-benefits-of-a-following-regular-truck-maintenance-schedule/',
    image: '/images/2022/09/Key-Benefits-of-a-Following-Regular-Truck-Maintenance-Schedule_image.jpg',
    alt: 'Key Benefits of a Following Regular Truck Maintenance Schedule',
    date: 'Mar 18, 2023',
    title: 'Key Benefits of a Following Regular Truck Maintenance Schedule',
    excerpt: 'If you are a Commercial truck owner, let us tell you, there is a lot that goes into this other than simply Purchasing a fleet and just booming it on the road for business. By this means, we mean keepi…',
  },
  {
    href: 'https://srbequipment.ca/blog/the-top-10-truck-repairs-every-owner-should-know-about/',
    image: '/images/2023/03/The-Top-10-Truck-Repairs-Every-Owner-Should-Know-About_image.jpg',
    alt: 'Top 10 Truck Repairs Every Owner Should Know',
    date: 'Mar 17, 2023',
    title: 'Top 10 Truck Repairs Every Owner Should Know',
    excerpt: 'Discover the top 10 truck repairs to avoid costly breakdowns. Keep your truck reliable—get expert help and maintenance from the team at SRB Equipment.',
  },
  {
    href: 'https://srbequipment.ca/blog/cost-of-commercial-vehicle-inspection/',
    image: '/images/2023/03/3-Factors-That-Affect-The-Cost-Of-Commercial-Vehicle-Inspection.jpg',
    alt: 'Why Vehicle Inspections Matter and What Affects Their Cost?',
    date: 'Mar 3, 2023',
    title: 'Why Vehicle Inspections Matter and What Affects Their Cost?',
    excerpt: 'Every commercial vehicle driver must conduct CVIP; therefore, many of you might be concerned about this cost. This Blog will give you a complete breakdown of the factors that affect the price of Comme…',
  },
  {
    href: 'https://srbequipment.ca/blog/tips-to-consider-while-buying-a-battery-for-your-semi-truck/',
    image: '/images/2023/02/Tips-to-Consider-While-Buying-a-Battery-for-Your-Semi-Truck_image.jpg',
    alt: 'Tips to Consider While Buying a Battery for Your Semi-Truck',
    date: 'Feb 25, 2023',
    title: 'Tips to Consider While Buying a Battery for Your Semi-Truck',
    excerpt: 'The best way to avoid battery problems is to avoid common mistakes drivers make while buying batteries for their semi-trucks. Here are some of the tips for selecting a battery for your semi-truck.',
  },
  {
    href: 'https://srbequipment.ca/blog/how-to-maximize-your-trucks-performance/',
    image: '/images/2023/02/How-To-Maximize-Your-Trucks-Performance_image.jpg',
    alt: 'How To Maximize Your Truck’s Performance?',
    date: 'Feb 17, 2023',
    title: 'How To Maximize Your Truck’s Performance?',
    excerpt: 'Trucks are known for their power, and If your truck isn’t functioning to its maximum capacity, it’ll be challenging to take it to the next level. There are many ways to maximize it. SRB Eq…',
  },
  {
    href: 'https://srbequipment.ca/blog/choosing-the-right-trailer-tire/',
    image: '/images/2023/02/Choosing-the-Right-Trailer-Tire_image.jpg',
    alt: 'Choosing the Right Trailer Tire',
    date: 'Feb 3, 2023',
    title: 'Choosing the Right Trailer Tire',
    excerpt: 'Having the right tires on your trailer is essential for hassle-free and successful transportation or road trips. As it is about safety and efficiency, always choose the right one. We’ve compiled…',
  },
  {
    href: 'https://srbequipment.ca/blog/mobile-trailer-repair-can-save-time-and-money/',
    image: '/images/2023/01/Mobile-Trailer-Repair-Can-Save-Time-and-Money_image.jpg',
    alt: 'Mobile Trailer Repair Can Save Time and Money',
    date: 'Jan 27, 2023',
    title: 'Mobile Trailer Repair Can Save Time and Money',
    excerpt: 'While working as a trucker, your vehicle and trailer need to be in top-notch form to ensure you can get every job done on time while staying safe on the road. An unmaintained vehicle or trailer can le…',
  },
  {
    href: 'https://srbequipment.ca/blog/what-are-the-main-parts-of-professional-trailer-repair-services/',
    image: '/images/2023/01/What-Are-The-Main-Parts-Of-Professional-Trailer-Repair-Services.jpg',
    alt: 'What Are The Main Parts Of Professional Trailer Repair Services?',
    date: 'Jan 20, 2023',
    title: 'What Are The Main Parts Of Professional Trailer Repair Services?',
    excerpt: 'Trailers, just like vehicles or any other machinery, eventually break down. Broken roads, steep hills, and heavy loads can affect the life of your trailer. Moreover, if avoiding preventive Maintenance…',
  },
  {
    href: 'https://srbequipment.ca/blog/when-should-you-have-your-trucks-steering-suspension-systems-checked/',
    image: '/images/2023/01/When-Should-You-Have-Your-Trucks-Steering-Suspension-Systems-Checked.jpg',
    alt: 'When Should You Have Your Truck’s Steering & Suspension Systems Checked?',
    date: 'Jan 14, 2023',
    title: 'When Should You Have Your Truck’s Steering & Suspension Systems Checked?',
    excerpt: 'The steering and suspension systems are essential for your safety and comfort because the suspension system holds up your truck and the load you\'re carrying. In contrast, the steering system keeps you…',
  },
  {
    href: 'https://srbequipment.ca/blog/five-things-that-can-damage-your-semi-truck/',
    image: '/images/2023/01/Five-Things-That-Can-Damage-Your-Semi-Truck.jpg',
    alt: 'Five Things That Can Damage Your Semi-Truck',
    date: 'Jan 4, 2023',
    title: 'Five Things That Can Damage Your Semi-Truck',
    excerpt: 'Avoid truck breakdowns with simple maintenance tips. Learn what causes most semi-truck damage and why SRB Equipment is Edmonton’s trusted repair shop',
  }
];
